### ISSUE TITLE
[UserStory] Retain menu item and title bar button functionality while audio is playing

### ISSUE THREAD

**Issue by ccason1** [MetroCS/imagelab#13]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a user of ImageLab
I want menu items and title bar buttons to still be functional while audio is playing
so that I retain control over the application while audio is playing.

## Acceptance Criteria

* Menu items are functional while audio is playing

### Scenario 1
Given that audio is playing
when I click on the title bar button to close the program
then the program closes.

### Scenario 2

Given that audio is playing
when I click on a menu item
then the menu item is functional.

**Comment by jody** [comment]
Outcome and Acceptance Criteria are vague (e.g., "buttons", "do anything else with ImageLab").

The issue appears to be related to whether the product interface behaves in a modal or non-modal fashion, and, in particular what support is desired for parallel processing.

This is indicative of an epic.  Adding "epic" label.

**Comment by jody** [comment]
New Title suggests that there is no audio functionality present in the product, which is not the case.

It is OK (and desirable) to make the title specific to the issue.  Most developers/maintainers will only see the title, so it is best to have it capture the intent (albeit in brief).

**Comment by jody** [comment]
Scenario 1 is confusing.

If the audio is already playing, why does the user "press the 'play' menu button"?

Why should the user need to select any menu item in order to be "able to close the current window or create a new window"?

**Comment by seboss123** [comment]
I would like to be assigned to this issue, please. @jody

**Comment by jody** [comment]
The acceptance criteria haven't been vetted and this has a label "epic", so there's no way to know when and whether to close this issue.  For example, if the user closes the window from which the "Play" was originated, should the "playing" halt?

This epic needs to be more fully developed as component user stories.

**Comment by jody** [comment]
Addressed by PR #27
